config/routes.rb
Rails.application.routes.draw do
  
  root to: 'public/homes#top'
  
  devise_for :end_users, controllers: {
   sessions:      'public/sessions',
   passwords:     'public/passwords',
   registrations: 'public/registrations'
  }
  
  scope module: :public do
   get 'end_users/mypage', :to => "end_users#show"
   patch 'end_users/mypage', :to => "end_users#update"
   get 'end_users/mypage/edit', :to => "end_users#edit"
   get 'end_users/mypage/confirm', :to => "end_users#confirm"
   patch 'end_users/mypage/unsubscribe', :to => "end_users#unsubscribe"
   get 'end_users/mypage/addresses', :to => "addresses#index"
   post 'end_users/mypage/addresses', :to => "addresses#create"
   get 'end_users/mypage/orders', :to => "orders#index"
   get 'items', :to => "items#index", as: :items
   get 'item/:id', :to => "items#show", as: :item
   get 'cart_items', :to => "cart_items#index"
   post 'cart_items', :to => "cart_items#create"
   patch 'cart_items/:id', :to => "cart_items#update" , as: :cart_item
   delete 'cart_items/:id', :to => "cart_items#destroy"
   delete 'cart_items', :to => "cart_items#destroy_all" , as: :destroy_all
   post 'orders', :to => "orders#create", as: :orders 
   get 'orders/new', :to => "orders#new", as: :orders_new
   post 'orders/confirm', :to => "orders#confirm", as: :orders_confirm
   get 'orders/done', :to => "orders#done", as: :orders_done
   
   
   
  end
  
  devise_for :admins,  path: 'admin', controllers: {
   sessions:      'admin/sessions',
   passwords:     'admin/passwords'
  }
  
  namespace :admin do
   get '', :to => "homes#top"
   get 'customers/index', :to => "customers#index"
   get 'genres', :to => "genres#index"
   post 'genres', :to => "genres#create"
   patch 'genres/:id', :to => "genres#update", as: :genres_update
   get 'genres/:id/edit', :to => "genres#edit" , as: :genres_edit
   get 'items', :to => "items#index"
   get 'items/new', :to => "items#new"
   post 'items/new', :to => "items#create"
   get 'items/:id', :to => "items#show", as: :item
   patch 'items/:id', :to => "items#update"
   get 'items/:id/edit', :to => "items#edit", as: :item_edit
   get 'orders', :to => "orders#index", as: :orders
   get 'orders/:id', :to => "orders#show", as: :order
   patch 'orders/:id', :to => "orders#update"
   patch 'order_details/:id', :to => "order_details#update", as: :order_detail
 
  end

end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :end_user
    
    def display_address
        '〒'  + self.postal_code + ' ' + self.address + ' ' + self.name
    end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :end_user
    belongs_to :item
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :email, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :phone_number, presence: true
  validates :address, presence: true
  validates :postal_code, presence: true 
  
  has_many :cart_items, dependent: :destroy
  has_many :orders
  has_many :addresses, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :genre
    has_many :cart_items, dependent: :destroy
    has_many :order_details, dependent: :destroy
    has_one_attached :image
    
    def self.search(search)
        
      if search 
        Item.where(['name LIKE ?', "%#{search}%"])
      else
        Item.all
      end
    end
    
    def get_image(width, height)
      unless image.attached?
        file_path = Rails.root.join('app/assets/images/no_image.jpg')
        image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
      end
      image.variant(resize_to_limit: [width, height]).processed
    end
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :end_user
    
    has_many :order_details, dependent: :destroy
    
    enum status:{
        p_wait: 0, 
        p_done: 1,
        making: 2,
        s_wait: 3, 
        s_done: 4
    }
    
    enum payment_method:{
        credit: 0,
        bank: 1,
    }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :item
    belongs_to :order
    
    enum making_status:{
        m_no: 0, 
        m_wait: 1,
        m_ing: 2, 
        m_done: 3
    }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
    
    def index
        @new_genre = Genre.new
        @genres = Genre.all
    end
    
    def create
        genre = Genre.new(genre_params)
        genre.save
        redirect_to admin_genres_path
    end
    
    def edit
        @genre = Genre.find(params[:id])
    end
    
    def update
        @genre = Genre.find(params[:id])
        @genre.update(genre_params)
        redirect_to admin_genres_path
    end
    
    private
    
    def genre_params
        params.require(:genre).permit(:name)
    end
    
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
    def top
        @orders = Order.all
    end
    

    
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    
    def index
        @items = Item.search(params[:search])
        @search = params[:search]
    end
    
    def new
        @item = Item.new
    end
    
    def create
        item = Item.new(item_params)
        item.save
        redirect_to admin_item_path(item.id)
    end
    
    def show
    end
    
    def edit
        @item = Item.find(params[:id])
    end
    
    def update
        item = Item.find(params[:id])
        item.update(item_params)
        redirect_to admin_items_path
    end
    
    def destroy
        item = Item.find(params[:id])
        item.destroy
        redirect_to admin_items_path
    end
    
    private
    
    def item_params
        params.require(:item).permit(:genre_id, :name, :introduction, :price, :image, :is_active)
    end
    
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    
    # def after_sign_out_path_for(resource)
    #   case resource
    #   when Admin
    #     root_path
    #   when EndUser
    #     root_path
    #   end
    # end

    def after_sign_up_path_for(resource)
        end_users_mypage_path
    end
    
    
    protected
    
    def configure_permitted_parameters
		added_attrs = [ :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :phone_number]

		devise_parameter_sanitizer.permit(:sign_up, keys: added_attrs)
	end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/_nav.html.erb
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <%= link_to "LOGO", root_path, class: 'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <!--サインイン状態での表示-->
          <% if admin_signed_in? %>
            <li>
              <%= link_to admin_items_path, class: "nav-link text-light" do %>
                <i class="fas fa-link"></i>商品一覧
              <% end %>
            </li>
            <li>
              <%= link_to admin_customers_index_path, class: "nav-link text-light" do %>
                <i class="fas fa-link"></i>会員一覧
              <% end %>
              
            </li>
            <li>
              <%= link_to admin_path, class: "nav-link text-light" do %>
                <i class="fas fa-link"></i>注文履歴一覧
              <% end %>
            </li>
            
            <li>
              <%= link_to admin_genres_path, class: "nav-link text-light" do %>
                <i class="fas fa-link"></i>ジャンル一覧
              <% end %>
            </li>
            
            <li>
              <%= link_to destroy_admin_session_path, class: "nav-link text-light", method: :delete do %>
                <i class="fas fa-sign-out-alt "></i>ログアウト
              <% end %>
            </li>
            <li>
            <%= form_tag(admin_items_path,:method => 'get') do %>
              <%= text_field_tag :search %>
              <%= submit_tag '検索', :name => nil %>
            <% end %>
            </li>
          <% else %>
          <!--ログアウト状態での表示-->

          <% end %>
        </ul>
      </div>
  </nav>

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>