config/routes.rb
Rails.application.routes.draw do
  
  root to: 'public/homes#top'
  
  devise_for :end_users, controllers: {
   sessions:      'public/sessions',
   passwords:     'public/passwords',
   registrations: 'public/registrations'
  }
  
  scope module: :public do
   get 'end_users/mypage', :to => "end_users#show"
   patch 'end_users/mypage', :to => "end_users#update"
   get 'end_users/mypage/edit', :to => "end_users#edit"
   get 'end_users/mypage/confirm', :to => "end_users#confirm"
   patch 'end_users/mypage/unsubscribe', :to => "end_users#unsubscribe"
   get 'end_users/mypage/addresses', :to => "addresses#index"
   post 'end_users/mypage/addresses', :to => "addresses#create"
   get 'end_users/mypage/orders', :to => "orders#index"
   get 'items', :to => "items#index", as: :items
   get 'item/:id', :to => "items#show", as: :item
   get 'cart_items', :to => "cart_items#index"
   post 'cart_items', :to => "cart_items#create"
   patch 'cart_items/:id', :to => "cart_items#update" , as: :cart_item
   delete 'cart_items/:id', :to => "cart_items#destroy"
   delete 'cart_items', :to => "cart_items#destroy_all" , as: :destroy_all
   post 'orders', :to => "orders#create", as: :orders 
   get 'orders/new', :to => "orders#new", as: :orders_new
   post 'orders/confirm', :to => "orders#confirm", as: :orders_confirm
   get 'orders/done', :to => "orders#done", as: :orders_done
   
   
   
  end
  
  devise_for :admins,  path: 'admin', controllers: {
   sessions:      'admin/sessions',
   passwords:     'admin/passwords'
  }
  
  namespace :admin do
   get '', :to => "homes#top"
   get 'customers/index', :to => "customers#index"
   get 'genres', :to => "genres#index"
   post 'genres', :to => "genres#create"
   patch 'genres/:id', :to => "genres#update", as: :genres_update
   get 'genres/:id/edit', :to => "genres#edit" , as: :genres_edit
   get 'items', :to => "items#index"
   get 'items/new', :to => "items#new"
   post 'items/new', :to => "items#create"
   get 'items/:id', :to => "items#show", as: :item
   patch 'items/:id', :to => "items#update"
   get 'items/:id/edit', :to => "items#edit", as: :item_edit
   get 'orders', :to => "orders#index", as: :orders
   get 'orders/:id', :to => "orders#show", as: :order
   patch 'orders/:id', :to => "orders#update"
   patch 'order_details/:id', :to => "order_details#update", as: :order_detail
 
  end

end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :end_user
    
    has_many :order_details, dependent: :destroy
    
    enum status:{
        p_wait: 0, 
        p_done: 1,
        making: 2,
        s_wait: 3, 
        s_done: 4
    }
    
    enum payment_method:{
        credit: 0,
        bank: 1,
    }

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
    
    def index
    end
    
    def show
        @order = Order.find(params[:id])
    end
    
    def update
        order = Order.find(params[:id])
        order.update(order_param)
        
        if order.status == "p_done"
            order.order_details.each do |order_detail|
                order_detail.update(making_status: "m_wait")
            end
        end
        
        
        redirect_to admin_order_path(order.id)
    end
    

    
    
    private
    
    def order_param
        params.require(:order).permit(:status)
    end
    

    
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<%= render 'admin/nav'%> 

<div class = "container">



</div>

app/views/admin/orders/show.html.erb
<%= render 'admin/nav'%> 
<div class = "container">
    <div class="row title">
        <div class = "col-md-2 offset-1">
            <h4>注文履歴詳細</h4>
        </div>
    </div>
    <div class = "row title">
        <div class = "col-12">
            <table class = "table table-borderless">
                <tbody>
                    <%= form_with model: @order, url: admin_order_path(@order.id),  local: true do |f| %>
                        <tr>
                            <th scope = "row" style = "width:20%">購入者</th>
                            <td style = "width:80%"><%= @order.end_user.last_name %><%= @order.end_user.first_name %></td>
                        </tr>
                        <tr>
                            <th scope = "row" style = "width:20%">注文日</th>
                            <td style = "width:80%"><%= @order.created_at.strftime('%Y/%m/%d') %></td>
                        </tr>
                        <tr>
                            <th scope = "row" style = "width:20%">配送先</th>
                            <td style = "width:80%">〒<%= @order.postal_code %> <%= @order.address %></td>
                        </tr>
                        <tr>
                            <th scope = "row" style = "width:20%"></th>
                            <td style = "width:80%"><%= @order.name %></td>
                        </tr>
                        <tr>
                            <th scope = "row" style = "width:20%">支払い方法</th>
                            <td style = "width:80%"><%= @order.payment_method_i18n %></td>
                        </tr>
                        <tr>
                            <th>注文ステータス</th>
                            <td style = "width:20%"><%= f.select :status, [["入金待ち", "p_wait"], ["入金確認", "p_done"], ["制作中", "making"], ["発送準備", "s_wait"], ["発送済み", "s_done"]],　selected: @order.status %></td>
                        </tr>
                        <tr>
                            <th></th>
                            <td ><%= f.submit "更新",class: 'btn btn-sm btn-success btn-sm ' %></td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
    <div class = "row title">
        <div class = "col-12">
            <table class = "table ">
                <thead>
                    <th scope = "col">商品名</th>
                    <th scope = "col">単価(税込)</th>
                    <th scope = "col">数量</th>
                    <th scope = "col">小計</th>
                    <th scope = "col" style = "width:13%">制作ステータス</th>
                    <th scope = "col" style = "width:5%">
                    </th>
                </thead>
                <tbody>
                    <% total = 0 %>
                    <% @order.order_details.each do |order_detail|%>
                        <tr>
                            <td><%= order_detail.item.name%></td>
                            <td><%= (order_detail.price * 1.1).to_i %></td>
                            <td><%= order_detail.amount%></td>
                            <td>
                                <%= (order_detail.price * 1.1 * order_detail.amount).to_i  %>
                                <% total +=  (order_detail.price * 1.1 * order_detail.amount).to_i %>
                            </td>
                            <%= form_with model: order_detail, url: admin_order_detail_path(order_detail.id),  local: true do |f| %>
                                <td><%= f.select :making_status, [["制作不可", "m_no"], ["制作待ち", "m_wait"], ["制作中", "m_ing"], ["制作完了", "m_done"]],　selected: order_detail.making_status %></td>
                                <td ><%= f.submit "更新",class: 'btn btn-sm btn-success btn-sm btn-block' %></td>
                            <%end%>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
    <div class = "row">
        <div class = "col-3 offset-9">
            <table class = "table table-borderless">
                <tbody>
                    <tr>
                        <th cope = "row" style = "width:50%">商品合計</th>
                        <td style = "width:80%"><%= total %></td>
                    </tr>
                    <tr>
                        <th cope = "row" style = "width:50%">送料</th>
                        <td style = "width:80%"><%= @order.shipping_cost %></td>
                    </tr>
                    <tr>
                        <th cope = "row" style = "width:50%">請求金額合計</th>
                        <td style = "width:80%"><%= @order.shipping_cost + total %></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>