config/routes.rb
Rails.application.routes.draw do
  
  root to: 'public/homes#top'
  
  devise_for :end_users, controllers: {
   sessions:      'public/sessions',
   passwords:     'public/passwords',
   registrations: 'public/registrations'
  }
  
  scope module: :public do
   get 'end_users/mypage', :to => "end_users#show"
   patch 'end_users/mypage', :to => "end_users#update"
   get 'end_users/mypage/edit', :to => "end_users#edit"
   get 'end_users/mypage/confirm', :to => "end_users#confirm"
   patch 'end_users/mypage/unsubscribe', :to => "end_users#unsubscribe"
   get 'end_users/mypage/addresses', :to => "addresses#index"
   post 'end_users/mypage/addresses', :to => "addresses#create"
   get 'end_users/mypage/orders', :to => "orders#index"
   get 'items', :to => "items#index", as: :items
   get 'item/:id', :to => "items#show", as: :item
   get 'cart_items', :to => "cart_items#index"
   post 'cart_items', :to => "cart_items#create"
   patch 'cart_items/:id', :to => "cart_items#update" , as: :cart_item
   delete 'cart_items/:id', :to => "cart_items#destroy"
   delete 'cart_items', :to => "cart_items#destroy_all" , as: :destroy_all
   post 'orders', :to => "orders#create", as: :orders 
   get 'orders/new', :to => "orders#new", as: :orders_new
   post 'orders/confirm', :to => "orders#confirm", as: :orders_confirm
   get 'orders/done', :to => "orders#done", as: :orders_done
   
   
   
  end
  
  devise_for :admins,  path: 'admin', controllers: {
   sessions:      'admin/sessions',
   passwords:     'admin/passwords'
  }
  
  namespace :admin do
   get '', :to => "homes#top"
   get 'customers/index', :to => "customers#index"
   get 'genres', :to => "genres#index"
   post 'genres', :to => "genres#create"
   patch 'genres/:id', :to => "genres#update", as: :genres_update
   get 'genres/:id/edit', :to => "genres#edit" , as: :genres_edit
   get 'items', :to => "items#index"
   get 'items/new', :to => "items#new"
   post 'items/new', :to => "items#create"
   get 'items/:id', :to => "items#show", as: :item
   patch 'items/:id', :to => "items#update"
   get 'items/:id/edit', :to => "items#edit", as: :item_edit
   get 'orders', :to => "orders#index", as: :orders
   get 'orders/:id', :to => "orders#show", as: :order
   patch 'orders/:id', :to => "orders#update"
   patch 'order_details/:id', :to => "order_details#update", as: :order_detail
 
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items, dependent: :destroy
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
    
    def index
        @new_genre = Genre.new
        @genres = Genre.all
    end
    
    def create
        genre = Genre.new(genre_params)
        genre.save
        redirect_to admin_genres_path
    end
    
    def edit
        @genre = Genre.find(params[:id])
    end
    
    def update
        @genre = Genre.find(params[:id])
        @genre.update(genre_params)
        redirect_to admin_genres_path
    end
    
    private
    
    def genre_params
        params.require(:genre).permit(:name)
    end
    
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<%= render 'admin/nav'%> 
<div class = "container">
 <div class = "raw title">
  <h4>ジャンル編集</h4>
 </div>
 
 
 <%= form_with model: @genre , url: admin_genres_update_path(@genre.id) , local: true do |f| %>
     <div class = "row field title">
      <div class = "col-md-2">
        <%= f.label "ジャンル名" %>
      </div>
      <div class = "col-2">
        <%= f.text_field :name, autofocus: true %>
      </div>
      <div class = "col-2 ">
          <%= f.submit "変更を保存",class: 'btn btn-sm btn-success btn-sm btn-block w-100px ' %>
      </div>
    </div>
 <% end %>
 
</div>

app/views/admin/genres/index.html.erb
<%= render 'admin/nav' %> 
<div class = "container">
        <div class="row title">
            <div class = "col-md-4 offset-1">
                <h4>ジャンル一覧・追加</h4>
            </div>
        </div>
        <%= form_with model: @new_genre, url: admin_genres_path, local: true do |f|%>
            <div class = "row title">
                <div class = col-2>
                    <%= f.label "ジャンル名" %>
                </div>
                <div class = col-3>
                    <%= f.text_field :name, :placeholder => "ジャンル",:size =>"25x10"  %>
                </div>
                <div class = col-2>
                    <%= f.submit "新規登録",class: 'btn btn-sm btn-success btn-sm btn-block '  %>
                </div>
            </div>
        <% end %>
        <div class = "row title">
            <table class ="table col-4">
                <thead class = "thead-light">
                    <tr>
                        <th scope = "col">ジャンル</th>
                        <th scope = "col"></th>
                    </tr>
                </thead>
                <tbody>
                    <% @genres.each do |genre|%>
                        <tr>
                            <td style = "width:30%"><%= genre.name %></td>
                            <td style = "width:15%"><%= link_to  "編集する", admin_genres_edit_path(genre.id), class: 'btn btn-sm btn-success btn-sm btn-block' %></td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
</div>